### ISSUE TITLE
Enhancement about Upvote  

### ISSUE THREAD

**Issue by Libert19** [eSteemApp/esteem#100]
While upvoting posts upvote icon takes 5-6 secs to turn to blue sometimes I have to click again to make sure app registers my action. If you can make something like swiping from left to right would upvote the post that would be better.

**Comment by feruzm** [comment]
thanks for report... It takes 3 seconds to record action to blockchain and extra secs might be network lagging. 

Are you seeing loading/spinner when voting is in process?

Swiping from left to right to upvote post, that seem good idea although wouldn't that cause issue when you are scrolling through post?!

**Comment by Libert19** [comment]
No it doesn't, but while upvoting thread it does. 

I think it won't be bothersome if app only register action when user would Swipe  post (left to right) nearly half way.

**Comment by feruzm** [comment]
Yes, for comments it doesn't show spinner. I have found that comment votes are not turning button to blue after action is registered. I have applied fix for that in coming release...
