### ISSUE TITLE
Pressing back from post loads everything again 

### ISSUE THREAD

**Issue by Libert19** [eSteemApp/esteem#101]
After reading some post from any tab (feed, trending,..) when I press back either with mobile key or from app it loads every posts again and takes me to the first post. 

This is really frustrating when you are half way down on some topic list and you have to scroll everything again to go to the original position.

**Comment by feruzm** [comment]
There are 2 cases,

* caching position would save bandwidth and solve this issue but number of votes, comments or fresh data of post will not be available.
* not caching would refresh page everytime

if we are okay with 1st case, this can be rolled out with next version.

**Comment by Libert19** [comment]
I guess first one would be better.
