### ISSUE TITLE
App hangs when opening thread with so many comments 

### ISSUE THREAD

**Issue by Libert19** [eSteemApp/esteem#102]
As the title says, when I open some thread which had hundreds of comments (example, Dan's resignation thread) app becomes unresponsive.

**Comment by feruzm** [comment]
you are right, for that reason we will have `fetch comments`, will be separate action and it will solve this... currently processing large number of comments takes time and resources.

**Comment by feruzm** [comment]
I have improved fetching and processing post if they have large number of comments, it will be included in next release. Although I will need to spend more time on this to optimize comments fetching separately.
