### ISSUE TITLE
Only 0$ (zero) shown on all posts

### ISSUE THREAD

**Issue by TAMustafa** [eSteemApp/esteem#104]
Hi brother, since this morning there is just an 0$ amount (zero) shown on (all) posts. Up-voting and commenting seems to work fine but even after up-voting the dollar amount remains zero.

**Comment by feruzm** [comment]
Thank you, I am adding fix to next release!

**Comment by TAMustafa** [comment]
Thank you.

**Comment by Libert19** [comment]
I think it was server issue. I changed it now works fine :)

**Comment by feruzm** [comment]
Yes, I have mentioned that to someone via comment. it was due to steemit.com upgraded to latest hf17. But temporary fix would be to change server and minor release is coming tomorrow for both Android and iOS.
