### ISSUE TITLE
View jump back on newest post

### ISSUE THREAD

**Issue by TAMustafa** [eSteemApp/esteem#105]
With the new version after I read and exit a post, I get right back to the top showing the newest posts and not at my previous scrolling position. 

I don't recall that it was like this in the previous version, back than when I read a post and went back I landed at the same post and could continue from there.

**Comment by feruzm** [comment]
Yes, we have changed it because some users requested to get fresh content everytime but now changing it back to better caching model. Next release will have an improvements... Thank you!
