### ISSUE TITLE
PIN code

### ISSUE THREAD

**Issue by feruzm** [eSteemApp/esteem#154]
Numbers padding and bigger sizing to allow better visibility

**Comment by maxomaniak** [comment]
Number pad moves down after having typed first number.
![image](https://user-images.githubusercontent.com/7907436/27520353-d3e3d86e-5a09-11e7-88fb-649ea82475b6.png)

**Comment by 4Ykw** [comment]
Confirmed on iOS too.

**Comment by feruzm** [comment]
Does it cause any issues or uneasiness, guys ?

**Comment by maxomaniak** [comment]
Yes sir!
I don't use PIN for that reason. Whenever I want to log in quickly I sometimes enter my PIN incorrectly. Things like these are annoying for 'quick users'. Also it's not what a user would expect. 
I'm a front-end developer. I don't mind helping out with coding/styling/usability but I don't really know how GitHub works.

**Comment by 4Ykw** [comment]
Uneasiness... I would say to fix when you have time. Not urgent in my view.

**Comment by feruzm** [comment]
v1.4.6 Android already has a fix, could you guys confirm if it is better?!
