### ISSUE TITLE
Night Mode enhancements

### ISSUE THREAD

**Issue by gruppler** [eSteemApp/esteem#155]
- Everything that's blue should be some shade of gray or red.
- Yellow in post title should be some shade of gray.
- Reputation score text is black on dark gray.
- Tags are not darkened correctly.
- Background should be black.
- Menu is not darkened.

**Comment by feruzm** [comment]
Some improvements are made with v1.4.6, please check back if you have more suggestions on how to improve it further. Thanks ;)
