### ISSUE TITLE
Error on commenting and up voting

### ISSUE THREAD

**Issue by amainz** [eSteemApp/esteem#159]
Hi,

I get the error `Broadcast error, try again! "[my username]", "posting"`

when trying to comment or up vote.

I use the version 1.4.5 on an Samsung Galaxy S7with Android 7.0

Thank you for your help.

**Comment by feruzm** [comment]
This is common issue on v1.4.5! Try to logout and login back with correct password and check again, please. Upcoming release has proper password checking that should solve this. Thanks!

**Comment by amainz** [comment]
Works now as following your suggestions. Thank you.
