### ISSUE TITLE
More accessible Voting Power slider

### ISSUE THREAD

**Issue by 4Ykw** [eSteemApp/esteem#162]
With the HF19, I find very hard to vote always with the voting power statically defined on settings. 

People with very low SP might not note the difference. But for whales or powered users, this might become a constraint.

Allowing the settings to choose if we get to choose every time the power to put into the vote or not, would be more useful with HF19 in my opinion.

Cheers

**Comment by feruzm** [comment]
Yes, voting power slider will have decimals from 0.01 to 100 with new release. 
Did you know you can tap and hold (0.5 sec) on voting button to open slider?

**Comment by 4Ykw** [comment]
No, I did not! Bummer! =) Issue closed! iOS get's laggy... so I usually need to wait for the loading times... to do that! =)
