### ISSUE TITLE
eSteem 1.4.6 (iOS) - Crash with messages after relaunch

### ISSUE THREAD

**Issue by 4Ykw** [eSteemApp/esteem#164]
Took the picture, just in case it would be useful.
<img src="https://user-images.githubusercontent.com/6281545/27845808-74e4144e-6186-11e7-9314-e5cf15635138.png" width="200"/>

I have also noticed that after the crash, the {{{ tend to appear sometimes for couple of milliseconds.

Then it happened that I watched a different post and this happened:
<img src="https://user-images.githubusercontent.com/6281545/27845811-7c921a88-6186-11e7-9578-0be92541167c.png" width="200"/>
<img src="https://user-images.githubusercontent.com/6281545/27845816-8897fc80-6186-11e7-9443-4963a9c460af.png" width="200"/>

The app keeps working fine.. after the last two messages.

Also the {{{ tags short appearance stopped happening after closing the app and reopening.

Cheers

**Comment by feruzm** [comment]
Thank you @4Ykw, really appreciate the report and screenshots... Have you seen these messages on 1.4.7 release?

**Comment by 4Ykw** [comment]
No, not yet. But I need to try some of the same testing techniques I used on the 1.4.6. During this weekend I will give it a good shot.

**Comment by 4Ykw** [comment]
It seems that is doing great now, at 1.4.7. No crash yet too... really looking great on these improvements.
