### ISSUE TITLE
Followers Count Mismatch in eSteem App

### ISSUE THREAD

**Issue by codingdefined** [eSteemApp/esteem#199]
When I load my profile in Esteem App, the follower's count is 736 whereas the following count is 582 as shown below.

![Screenshot_20171130-100312.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1512016680/q700bhkkj92hjuv3s1cf.png)

Whereas when I go to the Follow page the count changes, followers is 743 whereas following is 587 as shown below. 

![Screenshot_20171130-100332.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1512016687/v9jsku2ysc9kpisdzpmf.png)

I guess it is a bug in eSteem App.

### Expected Behaviour

The count of followers and following should be consistent in both the places.

### Device

Nokia 6, Android 7.1.2

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@codingdefined/followers-count-mismatch-in-esteem-app">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by AneilPatel05** [comment]
Agreed there is actually a bug. In my case the difference is two for both followers and follows
