### ISSUE TITLE
Esteem: 100%sp Sign showing on 50% sbd 50%sp post

### ISSUE THREAD

**Issue by yemmighto** [eSteemApp/esteem#208]
I was checking  through my post using esteem when I saw something surprising. There was a post I made few days ago and when I made the post it was in 50% SBD and 50% steem when I checked. But surprisingly  when I check through  esteem  app I could see it post been indicated as 100% sp because of the 100% sp been added to the post title on esteem app (screenshot below  in red) 
![IMG_20171229_073733_418.jpg](https://res.cloudinary.com/hpiynhbhq/image/upload/v1514529783/bguec2cooexcx8mcoaek.jpg)

Post at day 5 below

![IMG_20171226_155851_138.jpg](https://steemitimages.com/DQmRcszKK33GWjP3nWFz71Cmeven32uo7qFNXJKrA3EbWyA/IMG_20171226_155851_138.jpg)

You can easily  note the sign in red.  So I checked the post out using steemit.com and what indicated there  was 50% SBD and 50% sp because  there is no sign beside the post title (screenshot below) 

![Screenshot_20171226-160625.png](https://steemitimages.com/DQmXXoc68QybtubhwR5JkhraDwXS7HbzV4rY513KJytsxuk/Screenshot_20171226-160625.png)

On the steemit post there is no steem sign indicated.  

I don't know what is wrong,  first time seeing this

Esteem version 1.4.6

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@valchiz/esteem-detect-something-unusual">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by horpeyloaded** [comment]
please can you give more deatils about using video of gif

**Comment by nduchukwu** [comment]
Help needed am new here

**Comment by feruzm** [comment]
@yemmighto  that's not 100% steem power post indicator, that is promoted post indicator, meaning that post has been promoted with SBD...
