### ISSUE TITLE
Functional PIN is Created when Confirm PIN Field is Left Empty

### ISSUE THREAD

**Issue by thewizardstudio** [eSteemApp/esteem#214]
#### Expected Behavior
Leaving the Confirm PIN field empty when creating a PIN should result in no PIN being created and the user being prompted to enter the PIN correctly.

#### Actual Behavior
Leaving the Confirm PIN field empty when creating a PIN results in a functional PIN being created.

#### How to Reproduce
1. Launch eSteem 1.5.0 on Android 8.1.0
2. Click the 3 Horizontal Lines in the Upper Left
3. Select 'Settings'
4. Select 'Pin Code'
5. Enter '1111' on the Set Pin screen
6. Select the Android 'Back Button' on the Confirm Pin screen
7. Attempt to turn off the Pin Code and enter '1111' when prompted

---
    Device: Pixel 2 XL
    OS: Android 8.1.0
    App Version: 3.2.1
---

#### Recording of the Bug
![ConfirmPINBroke.gif](https://res.cloudinary.com/hpiynhbhq/image/upload/v1516485199/e3ykl7gbfrcrqf9cixzk.gif)

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@thewizard.studio/functional-pin-is-created-when-confirm-pin-field-is-left-empty">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by feruzm** [comment]
This issue is solved with v1.5.1, please check and confirm if you can. Thank you!
