### ISSUE TITLE
NaN years ago

### ISSUE THREAD

**Issue by rex4539** [esteemapp/esteem#229]
![img_2105](https://user-images.githubusercontent.com/227442/35781674-c42befa0-09f5-11e8-82a0-9b571ca0b808.png)

**Comment by rex4539** [comment]
This app appears to be abandoned. Retracting.

**Comment by feruzm** [comment]
@rex4539 this is not abandoned but upgraded to v2: https://github.com/esteemapp/esteem-mobile
We will soon archive this repo after officially depreciation of v1 from app stores.
