### ISSUE TITLE
Two button collapse if we change Language  to اردو

### ISSUE THREAD

**Issue by rockstar96969696** [eSteemApp/esteem#252]
#### Expected behavior
The Search option and the the other button for opening  slide options shoud work independently without any issu of collapsing.
There should  be a special arrangement for these options in اردو  selection in Language.
#### Actual behavior
When i change the Language  to اردو then two buttons of option and search option are collapsed and hard to press the main option button instead to search option.
#### How to reproduce
- Download Esteem App Version 1.5.1
- Change Language  from setting  to اردو  
![IMG-20180214-WA0006.jpg](https://res.cloudinary.com/hpiynhbhq/image/upload/v1518630804/a1gcygwnmtznfeik23me.jpg)
- Change English to اردو   
![IMG-20180214-WA0005.jpg](https://res.cloudinary.com/hpiynhbhq/image/upload/v1518630859/idswc0cv2euqyvazzk7c.jpg)
- Collapsed Buttons 

![IMG-20180214-WA0007.jpg](https://res.cloudinary.com/hpiynhbhq/image/upload/v1518630910/jzoybwzdnflutwwt9n3v.jpg)
* Operating system:Android Nougat 7.0
* Esteem: Version 1.5.1

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@faisalamin/two-button-collapse-if-we-change-language-to-ardw">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by feruzm** [comment]
version 1.5.2 resolves this!
