### ISSUE TITLE
Black list?

### ISSUE THREAD

**Issue by minbone** [eSteemApp/esteem#263]
Me and my friends got upvoted from esteeemapp for 6 consecutive days. But now all of us didn't get upvote for 2weeks . What is wrong? Give us a strong reason and we all are very disappointing about using esteemapp. @minbonekhant @pyaytheinkhine @shweyamoneko

**Comment by feruzm** [comment]
Visit Telegram or Discord channels for this type of questions, our moderators will help you with any questions.
