### ISSUE TITLE
Wrong time information is displayed on an uploaded picture saved in the esteem app gallery

### ISSUE THREAD

**Issue by kodeblacc** [eSteemApp/esteem#289]
#### Expected behavior
I expected that correct time of picture uploaded will be displayed on the inbuilt esteem gallery.

#### Actual behavior
After uploading a picture on a post on esteem app it automatically saves to the esteem inbuilt gallery for future use however the time the picture was uploaded is wrong. On my phone it displays 2hours ago

#### How to reproduce
- Download and launch the esteem app
- Make a post
- Upload an image from your file manager
- Try to upload an image again this time select gallery as an option
- Click manage
- The recently uploaded picture will be present but with a wrong time information which is confusing

* Device : Infinix note 4
* Operating system: Android 8.1.0
* Software Version: 1.5.1

#### Recording Of The Bug
https://vimeo.com/261730241

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@kodeblacc/wrong-time-information-is-displayed-on-an-uploaded-picture-saved-in-the-esteem-app-gallery">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by feruzm** [comment]
fixed, v1.5.2 will include this
