### ISSUE TITLE
Removing a bookmark: The bookmark above is deleted

### ISSUE THREAD

**Issue by kodeblacc** [eSteemApp/esteem#292]
#### Expected behavior
I expected that when I select a desired bookmark to be removed it'll be the bookmark removed
#### Actual behavior
When I try to remove a bookmark, it is not the desired bookmark that is removed but the one above it

#### How to reproduce
- download the esteem app from Google play store
- launch the app and allow all permissions
- login
- bookmark posts by clicking on the icon that looks like a book( bookmark a minimum of two posts)
- Locate the bookmarks tab on the left menu
- swipe from right to left to reveal options on a bookmark.(select the last bookmark)
- remove the bookmark and the one above is deleted
<hr>

* Device: Infinix note 4
* Operating system: Android 8.0
* Software version: 1.5.1

#### Recording Of The Bug
https://vimeo.com/261914819
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@kodeblacc/removing-a-bookmark-the-bookmark-above-is-deleted">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by feruzm** [comment]
fixed, 1.5.2 version is coming soon
