### ISSUE TITLE
esteem: Notifications settings are not saved

### ISSUE THREAD

**Issue by evisored** [eSteemApp/esteem#293]
#### Expected behavior
I hope to save the notification settings of vote, comment, follow, mentions and reblog.

#### Actual behavior

When I finished setting the vote notification, follow, comment, mentions and reblog.
Actually Save changes not sustained after quit the app.

#### How to reproduce
Step1: Launch eSteem app.

Step2: Go to settings menu and find 
notifications  submenu.

Step3: Select vote, comment, follows, mention,reblog and press the Switch button.

Step4: Tap on Save changes.

 *Operating system: Android 7.1.1 (Nougat)

*Device: Xiomi Mi Max 2

*App Version: eSteem v.1.5.1

#### Recording Of The Bug
https://www.youtube.com/watch?v=ohG-s0sGJqI    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@visored/esteem-notifications-are-not-saved">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by feruzm** [comment]
fixed, 1.5.2 version is coming soon
