### ISSUE TITLE
eSteem v1.6.0 -  Back Button Does Nothing While On Pincode Setup Screen

### ISSUE THREAD

**Issue by realrufans** [esteemapp/esteem#345]
#### Expected behavior
The back button ought to take the user away from the pin setup screen.

<Hr>

#### Actual behavior
The back button does nothing while the pin code setup screen is open.

<Hr>

#### How to reproduce
* Launch and sign in to eSteemapp
* swipe right and click on settings
* Click on the pincode button to setup a Pin
* Try clicking the back button of your device to leave the setup screen.

<Hr>

#### App version:
* eSteem v1.6.0
* Operating system: Android 8.1
* Model: Tecno Xpro

<Hr>

#### Recording Of The Bug
https://youtu.be/laeGk7YF5nU

**Comment by feruzm** [comment]
That's intentional to avoid bypassing pincode screen.

**Comment by realrufans** [comment]
Okay thank you .
User can bypass it by Entering  wrong pin code three times.

**Comment by feruzm** [comment]
Yes, that would reset or clear user credentials to keep their funds safe.

**Comment by realrufans** [comment]
Perfect 👍. I just confirmed it
