### ISSUE TITLE
Translations of views don't load (revert to English)

### ISSUE THREAD

**Issue by tibonova** [eSteemApp/esteem#36]
The translation of views (Trending, New, etc.) don't load. It shows the original (English) text there, while shows the translated (Hungarian) text everywhere in the app.

I've experienced this once in the past, but the problem disappeared while I used the app.
I've updated the app, and the problem came back. 

I'll update this when I've found out how it started working before.

**Comment by feruzm** [comment]
Thank you for reporting, translation of filters are not instant. But once you choose any other filter it should update with next language text. noted this to fix in upcoming release!

**Comment by tibonova** [comment]
I've tried changing between filters. They didn't update for me. Strange, because the solution was something like that.

**Comment by tibonova** [comment]
It's reloaded finally, when I changed not these filters (New, Trending, etc.) but navigating in the app menu. I visited the Market Place, though I don't think that specific detail matters but the fact that I moved away from Home and came back to it.

**Comment by feruzm** [comment]
As we have discussed in steemit.chat #esteem in next release we will have app reload when language is changed.

**Comment by feruzm** [comment]
Please also confirm if this is resolved on your devices.

**Comment by tibonova** [comment]
This was the first thing what I've done after refreshed the app (reading you announcement meanwhile).

I have to say that the problem still exist. 
To make sure, I've changed the language to Dolan (it's fun) and changed back to Hungarian. The app has been reloading each time, and the filters changing to the expected words. 
However, after I close the app and start it again, the filters reverts to English, no matter which language I'm using.

**Comment by feruzm** [comment]
Thank you, great find...   v1.3.8 uses `get_state` api that fetches post and comments and author details with one request but there is downside of processing all that data. I think it might be causing long delay when we have 40+ comments, need optimization

**Comment by feruzm** [comment]
thank you @tibonova, found the issue right after your detailed report.

**Comment by feruzm** [comment]
Closing this, if you encounter this again, please let me know. Thank you!
