### ISSUE TITLE
Error when voting on already voted post

### ISSUE THREAD

**Issue by kharoof** [eSteemApp/esteem#37]
The error occurs after reading an article and voting in the article. 

- When I navigate back to the main feed the article appears to be unvoted 
- When I try to vote again I get an error message
(See Screenshot)

![screenshot_20170113-065457](https://cloud.githubusercontent.com/assets/7195323/21921927/6232f1d6-d963-11e6-98c8-e2ce6a3cc1ba.png)

![screenshot_20170113-065431](https://cloud.githubusercontent.com/assets/7195323/21921939/73d6f112-d963-11e6-931d-cf049c55a4d2.png)

**Comment by feruzm** [comment]
Thank you for reporting, we add `pull down to refresh` functionality in next version which should solve this. The reason we are not refreshing posts again when you get back is to save bandwidth and unnecessary loads, but soon we will add better handle of individual posts.
