### ISSUE TITLE
Issue with payout values

### ISSUE THREAD

**Issue by kharoof** [eSteemApp/esteem#39]
On the post display in your blog section the payout values do not match what is shown on the Steemit website.
The payout value shown is the author reward but when you go into the detail shown the author reward shown is not correct. It looks like the app is taking off the curators reward from the authors reward. 

For Example
-------------------------------------------------------------------
**The App shows** 
![screenshot_20170114-205249](https://cloud.githubusercontent.com/assets/7195323/21958187/e812bf06-da9f-11e6-85bc-28ed4b3b4fb3.png)

---------------------------------------

**The Website shows**
![screenshot from 2017-01-14 21-28-51](https://cloud.githubusercontent.com/assets/7195323/21958232/75d1c3d6-daa1-11e6-9b62-3a3e7bfdc6cb.png)

**Comment by feruzm** [comment]
Thank you!
Past payout is `total_payout_value`
Author payout is `total_payout_value - curator_payout_value`
in app.

It might be that Steem was changed after couple hardfork to include only author payout on `total_payout_value`. I will make necessary changes ;)

**Comment by feruzm** [comment]
payout values also updated to reflect with other apps (steemit, busy, golos)
