### ISSUE TITLE
Comments don't load on some posts

### ISSUE THREAD

**Issue by tibonova** [eSteemApp/esteem#43]
I've first experienced while wanted to see the comments at [this post](https://steemd.com/steemit/@berniesanders/dan-still-trolling-ozchartart). That wasn't the only one, I don't know what is the difference between the post where it loads and the posts where it doesn't. I've tried it more times, with wifi and mobile data, same results.

**Comment by feruzm** [comment]
Thank you, great find...   v1.3.8 uses `get_state` api that fetches post and comments and author details with one request but there is downside of processing all that data. I think it might be causing long delay when we have 40+ comments, need optimization

**Comment by feruzm** [comment]
Fixed, v1.3.9
