### ISSUE TITLE
Replies and Comments without full Context

### ISSUE THREAD

**Issue by kharoof** [eSteemApp/esteem#45]
When you click into a comment or replies in the user section you don't get an option to see the full context. You only see the specific comment. 
This means it can make it difficult to reply to comments in the app. I am constantly switching to the browser to see what the post was about.

**Comment by feruzm** [comment]
thank you for posting this, I had this on todo list for this version 1.3.8 somewhat slipped the list, will make it priority for next release...profile page will get major refinement in 1.3.9

**Comment by feruzm** [comment]
Please revisit this with v1.3.9 if proper behavior is met! Thank you!

**Comment by feruzm** [comment]
Fixed 7d37f4f484a54a839cafa777354338fa59c53cb7 update will have this
