### ISSUE TITLE
Select External Browser Option

### ISSUE THREAD

**Issue by kharoof** [eSteemApp/esteem#46]
When you click on a link in the app it opens an in app browser. It would be useful to let users select an external browser to open links in.

**Comment by feruzm** [comment]
Do you mean like open in system browser? If system has more than 1 browsers, it either suggest to open with one of them or open with default one.

**Comment by kharoof** [comment]
When I click a link in a message it opens a browser. I don't think its my phone system browser. I have firefox set as my default browser app. its definitely not firefox. I thought it was some built in web browser in the esteem app. Either way its not the browser I would like to use and it would be good to be able to specify in the settings which browser you wanted to open links in.

**Comment by feruzm** [comment]
Yes, I meant to clarify flow, right now it opens in app browser, not system browser. Taking you suggestions it would be wise to use default system browser or give user a choice. marked as enhancement for next release. thank you. :)

**Comment by kharoof** [comment]
That sounds great.
