### ISSUE TITLE
Submit a Story Button

### ISSUE THREAD

**Issue by kharoof** [eSteemApp/esteem#49]
I would suggest adding submit a story/write new post button in a few more places in the app to make it easier to find.  

It would be good to see it in the navigation bar. When you get the nav bar on the left you currently you have to click into drafts then you can write but I don't think this is as intuitive as it could be. 

On the main feed screen you have to click the three dots at the top right before you get an option to submit a story. If it would fit it might be good to have a submit story button at the top but I dont think it would be as big a deal to put it here if it was included in the nav bar on the left. 

The last place where I think you should get an option is when your in a post and you click on the + Icon. You currently get options to Reblog, Gallery, Upvote and Reply. I think it would make sense to have a submit new story option here also.

**Comment by feruzm** [comment]
Have added extra button under Profile in Side menu. Closing this for now, there will be minor design work in future to improve user flow.
