### ISSUE TITLE
Lock up when opening post or trying to reply

### ISSUE THREAD

**Issue by oldambtster** [eSteemApp/esteem#50]
This occurs in version 1.3.8 for Android (5.1). When opening a post in the 'Profile' section or trying to reply it shows a loading image and the app freezes. Need to close it down and reopen the app.

This does only seem to be the case in the 'Profile' section.

**Comment by feruzm** [comment]
App freeze was reason of processing post, is improved with v1.3.9 release. Closing this as well, but feel free to leave a comment when you find more issues.

**Comment by oldambtster** [comment]
Seems it is okay now! Thanks!
