### ISSUE TITLE
Reputation, Voting Power, and Payout Totals

### ISSUE THREAD

**Issue by kharoof** [eSteemApp/esteem#67]
There are a few places in the app which seem to have stopped updating with refreshed values:

**- The Yellow arrow here showing voting power has stopped updating.**
**- The Pink arrow showing post payout shows the payout remaining rather than the post payout. these posts had a payout already. I dont think this is the expected behaviour here.**

![skitch](https://cloud.githubusercontent.com/assets/7195323/23332175/4b117852-fb6d-11e6-9a46-ef2d9ff23092.png)

- **The Reputation figure in this screen and voting power both have stopped updating.** 

![skitche](https://cloud.githubusercontent.com/assets/7195323/23332178/4d558b62-fb6d-11e6-8d7b-06fffc034607.png)

**Comment by feruzm** [comment]
Thank you for reporting! With multi-chain, user profile update function got broken during auto-refresh. v1.4.0 has fix and coming soon.

**Comment by feruzm** [comment]
please report back if issue is still persist after upgrade. thanks!
