### ISSUE TITLE
Возможность запуска нескольких копий приложения

### ISSUE THREAD

**Issue by vadbars** [eSteemApp/esteem#95]
Возможность запуска нескольких копий приложения - для golos и для steem.

Можно реализовать в виде виджетов (android), ярлыков (windows) или симлинков (linux).

**Comment by feruzm** [comment]
https://golos.io/ru--golos/@boddhisattva/odnovremennoe-ispolzovanie-mobilnogo-klienta-pod-android-esteem-dlya-raboty-s-golosom-i-steemit
