### ISSUE TITLE
Comments error

### ISSUE THREAD

**Issue by feruzm** [eSteemApp/esteem#97]
"Broadcast error, try again! reject(error)"

**Comment by feruzm** [comment]
Couldn't reproduce this error, possibly user had chain connection issues.

**Comment by richardcrill** [comment]
I get the same error every time I try to vote on a post

**Comment by apalkoff** [comment]
Same for me

**Comment by feruzm** [comment]
Hi @richardcrill and @apalkoff,
Are you guys trying using latest version 1.4.5? Error message handling was updated, you should be getting different error if any...
